<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mq5</string>
		<string>mqh</string>
	</array>
	<key>name</key>
	<string>MQL5</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#preprocessor</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#deprecated_mql4</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#security_warnings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unsupported_cpp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#modifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions_mql5</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functions_mql5_new</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#indicators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#event_handlers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#predefined_variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numerics</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blocks</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.mql5</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#todo_markers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.double-slash.mql5</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#todo_markers</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>todo_markers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>TODO/FIXME/XXX/BUG markers - flag for attention</string>
					<key>match</key>
					<string>\b(TODO|FIXME|XXX|BUG|HACK|UNDONE)\b:?.*</string>
					<key>name</key>
					<string>invalid.illegal.todo.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>NOTE/OPTIMIZE/WARNING markers - informational flags</string>
					<key>match</key>
					<string>\b(NOTE|OPTIMIZE|WARNING|DEPRECATED|REFACTOR|REVIEW)\b:?.*</string>
					<key>name</key>
					<string>invalid.warning.note.mql5</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.mql5</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.mql5</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.mql5</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.mql5</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>preprocessor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\s*(include|import)\s*[&lt;"](.*?)[&gt;"]</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.preprocessor.mql5</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.other.mql5</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>#\s*(define|undef|ifdef|ifndef|else|endif|property|resource)\b</string>
					<key>name</key>
					<string>keyword.control.preprocessor.mql5</string>
				</dict>
			</array>
		</dict>
		<key>deprecated_mql4</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 event handlers - replace with MQL5 OnInit/OnDeinit/OnTick</string>
					<key>match</key>
					<string>\b(init|deinit|start)\b(?=\s*\()</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.event-handler.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 trade functions - use MQL5 CTrade class or OrderSend</string>
					<key>match</key>
					<string>\b(OrderClose|OrderCloseBy|OrderDelete|OrderModify|OrderClosePrice|OrderCloseTime|OrderComment|OrderCommission|OrderExpiration|OrderLots|OrderMagicNumber|OrderOpenPrice|OrderOpenTime|OrderPrint|OrderProfit|OrderSelect|OrderStopLoss|OrderSwap|OrderSymbol|OrderTakeProfit|OrderTicket|OrderType|OrdersHistoryTotal|OrdersTotal)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.trade-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 account functions</string>
					<key>match</key>
					<string>\b(AccountBalance|AccountCredit|AccountCompany|AccountCurrency|AccountEquity|AccountFreeMargin|AccountFreeMarginCheck|AccountFreeMarginMode|AccountLeverage|AccountMargin|AccountName|AccountNumber|AccountProfit|AccountServer|AccountStopoutLevel|AccountStopoutMode)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.account-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 chart/window functions</string>
					<key>match</key>
					<string>\b(WindowBarsPerChart|WindowExpertName|WindowFind|WindowFirstVisibleBar|WindowHandle|WindowIsVisible|WindowOnDropped|WindowPriceMax|WindowPriceMin|WindowPriceOnDropped|WindowRedraw|WindowScreenShot|WindowsTotal|WindowTimeOnDropped|WindowXOnDropped|WindowYOnDropped|HideTestIndicators|IndicatorBuffers|IndicatorCounted|IndicatorDigits|IndicatorShortName|SetIndexArrow|SetIndexBuffer|SetIndexDrawBegin|SetIndexEmptyValue|SetIndexLabel|SetIndexShift|SetIndexStyle|SetLevelStyle|SetLevelValue)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.chart-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 time functions</string>
					<key>match</key>
					<string>\b(CurTime|Day|DayOfWeek|DayOfYear|Hour|Minute|Month|Seconds|TimeDay|TimeDayOfWeek|TimeDayOfYear|TimeHour|TimeMinute|TimeMonth|TimeSeconds|TimeYear|Year)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.time-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 string functions</string>
					<key>match</key>
					<string>\b(DoubleToStr|StrToDouble|StrToInteger|StrToTime|TimeToStr|CharToStr)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.string-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 array functions</string>
					<key>match</key>
					<string>\b(ArrayCopyRates|ArrayCopySeries|ArrayDimension)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.array-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 iXXXOnArray indicators</string>
					<key>match</key>
					<string>\b(iBandsOnArray|iCCIOnArray|iEnvelopesOnArray|iMAOnArray|iMomentumOnArray|iRSIOnArray|iStdDevOnArray)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.indicator-on-array.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 other functions</string>
					<key>match</key>
					<string>\b(MarketInfo|RefreshRates|Highest|Lowest|IsConnected|IsDemo|IsDllsAllowed|IsExpertEnabled|IsLibrariesAllowed|IsOptimization|IsStopped|IsTesting|IsTradeAllowed|IsTradeContextBusy|IsVisualMode|UninitializeReason|ClientTerminalName|TerminalName|TerminalPath|TerminalCompany|ScreenShot|PriceOnDropped|TimeOnDropped|FirstVisibleBar)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.other-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 object functions</string>
					<key>match</key>
					<string>\b(ObjectGet|ObjectSet|ObjectDescription|ObjectGetFiboDescription|ObjectSetFiboDescription|ObjectGetShiftByValue|ObjectGetValueByShift|ObjectGetValueByTime|ObjectSetText|ObjectType)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.object-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 file functions</string>
					<key>match</key>
					<string>\b(FileOpenHistory|FileReadNumber)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.file-function.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4 trading modes</string>
					<key>match</key>
					<string>\b(OP_BUY|OP_SELL|OP_BUYLIMIT|OP_SELLLIMIT|OP_BUYSTOP|OP_SELLSTOP|SELECT_BY_POS|SELECT_BY_TICKET|MODE_TRADES|MODE_HISTORY)\b</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.constant.mql5</string>
				</dict>
			</array>
		</dict>
		<key>security_warnings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>SECURITY: Lossy type casts that may lose financial precision</string>
					<key>match</key>
					<string>\(\s*(int|short|char|float)\s*\)</string>
					<key>name</key>
					<string>invalid.warning.lossy-cast.mql5</string>
				</dict>
			</array>
		</dict>
		<key>unsupported_cpp</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ exception handling - not available in MQL5</string>
					<key>match</key>
					<string>\b(try|catch|throw|noexcept)\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.exception.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ namespaces - not available in MQL5</string>
					<key>match</key>
					<string>\b(namespace|using)\s+\w+</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.namespace.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ STL containers - use MQL5 arrays or custom classes</string>
					<key>match</key>
					<string>\b(std::)?(vector|map|unordered_map|set|unordered_set|list|deque|queue|stack|priority_queue|array|forward_list|multimap|multiset|bitset|pair|tuple)\s*&lt;</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.stl-container.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ smart pointers - use raw pointers with careful management</string>
					<key>match</key>
					<string>\b(std::)?(unique_ptr|shared_ptr|weak_ptr|auto_ptr|make_unique|make_shared)\s*&lt;</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.smart-pointer.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ std:: prefix - standard library not available</string>
					<key>match</key>
					<string>\bstd::\w+</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.std-namespace.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ stream I/O - use Print/Comment/Alert instead</string>
					<key>match</key>
					<string>\b(cout|cin|cerr|clog|endl|ostream|istream|iostream|stringstream|ostringstream|istringstream|fstream|ifstream|ofstream)\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.iostream.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C memory allocation - use new/delete or ArrayResize</string>
					<key>match</key>
					<string>\b(malloc|calloc|realloc|free|memset|memcpy|memmove)\s*\(</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.c-memory.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ type deduction - explicitly declare types</string>
					<key>match</key>
					<string>\b(auto|decltype)\b(?!\s*\()</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.auto.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++11 nullptr - use NULL in MQL5</string>
					<key>match</key>
					<string>\bnullptr\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.nullptr.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ constexpr - use #define or const</string>
					<key>match</key>
					<string>\b(constexpr|consteval|constinit)\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.constexpr.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ lambda expressions</string>
					<key>match</key>
					<string>\[\s*[=&amp;]?\s*\]\s*\(</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.lambda.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ explicit type casts - use C-style or (type) casts</string>
					<key>match</key>
					<string>\b(static_cast|const_cast|reinterpret_cast)\s*&lt;</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.cast.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ concepts and requires</string>
					<key>match</key>
					<string>\b(concept|requires)\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.concept.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ coroutines</string>
					<key>match</key>
					<string>\b(co_await|co_yield|co_return)\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.coroutine.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ modules</string>
					<key>match</key>
					<string>\b(import|module|export)\b(?!\s+group)</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.module.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ standard headers - use MQL5 #include</string>
					<key>match</key>
					<string>#\s*include\s*&lt;(iostream|vector|string|map|set|algorithm|memory|functional|utility|cstdlib|cstdio|cstring|cmath|cassert|climits|cfloat|cctype|ctime)\s*&gt;</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.std-header.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ thread/atomic - MQL5 is single-threaded per EA</string>
					<key>match</key>
					<string>\b(std::)?(thread|mutex|lock_guard|unique_lock|condition_variable|atomic|future|promise|async)\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.threading.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ RTTI beyond dynamic_cast</string>
					<key>match</key>
					<string>\b(typeid|type_info)\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.rtti.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ friend keyword</string>
					<key>match</key>
					<string>\bfriend\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.friend.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ mutable keyword</string>
					<key>match</key>
					<string>\bmutable\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.mutable.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ volatile keyword</string>
					<key>match</key>
					<string>\bvolatile\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.volatile.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ register keyword</string>
					<key>match</key>
					<string>\bregister\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.register.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C goto statement - use structured control flow</string>
					<key>match</key>
					<string>\bgoto\b</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.goto.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: C++ inline keyword (compiler decides)</string>
					<key>match</key>
					<string>\binline\b</string>
					<key>name</key>
					<string>invalid.warning.unsupported-cpp.inline.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>UNSUPPORTED: Multiple inheritance syntax</string>
					<key>match</key>
					<string>:\s*(public|private|protected)\s+\w+\s*,\s*(public|private|protected)</string>
					<key>name</key>
					<string>invalid.illegal.unsupported-cpp.multiple-inheritance.mql5</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|switch|case|default|break|continue|for|do|while|return|new|delete)\b</string>
					<key>name</key>
					<string>keyword.control.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(operator|sizeof|this|template|typename|typedef|dynamic_cast|override|final)\b</string>
					<key>name</key>
					<string>keyword.other.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(__DATE__|__DATETIME__|__FILE__|__FUNCSIG__|__FUNCTION__|__LINE__|__PATH__|__MQLBUILD__|__MQL5BUILD__)\b</string>
					<key>name</key>
					<string>keyword.other.predefined.mql5</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(char|short|int|long|uchar|ushort|uint|ulong|bool|color|datetime|string|double|float|void|complex)\b</string>
					<key>name</key>
					<string>storage.type.primitive.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(enum|struct|class|interface|union)\b</string>
					<key>name</key>
					<string>storage.type.composite.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Matrix/Vector types (Build 3180+)</string>
					<key>match</key>
					<string>\b(matrix|vector|matrixf|vectorf)\b</string>
					<key>name</key>
					<string>storage.type.matrix.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 built-in structures</string>
					<key>match</key>
					<string>\b(MqlDateTime|MqlRates|MqlTick|MqlBookInfo|MqlTradeRequest|MqlTradeResult|MqlTradeCheckResult|MqlTradeTransaction|MqlParam|MqlCalendarValue|MqlCalendarCountry|MqlCalendarEvent)\b</string>
					<key>name</key>
					<string>storage.type.struct.mql5</string>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(const|private|protected|public|virtual|export|static|extern|input|sinput)\b</string>
					<key>name</key>
					<string>storage.modifier.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Input group for MT5 parameter organization</string>
					<key>match</key>
					<string>\binput\s+group\b</string>
					<key>name</key>
					<string>storage.modifier.input-group.mql5</string>
				</dict>
			</array>
		</dict>
		<key>event_handlers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>MQL5 event handlers</string>
					<key>match</key>
					<string>\b(OnInit|OnDeinit|OnTick|OnTimer|OnTrade|OnTradeTransaction|OnBookEvent|OnChartEvent|OnCalculate|OnTester|OnTesterInit|OnTesterDeinit|OnTesterPass|OnStart)\b</string>
					<key>name</key>
					<string>entity.name.function.event-handler.mql5</string>
				</dict>
			</array>
		</dict>
		<key>functions_mql5</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>MQL5 Account functions</string>
					<key>match</key>
					<string>\b(AccountInfoDouble|AccountInfoInteger|AccountInfoString)\b</string>
					<key>name</key>
					<string>support.function.account.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Trade functions</string>
					<key>match</key>
					<string>\b(OrderSend|OrderSendAsync|OrderCalcMargin|OrderCalcProfit|OrderCheck|OrderGetDouble|OrderGetInteger|OrderGetString|OrderGetTicket|OrdersTotal|PositionSelect|PositionSelectByTicket|PositionGetDouble|PositionGetInteger|PositionGetString|PositionGetSymbol|PositionGetTicket|PositionsTotal|HistorySelect|HistorySelectByPosition|HistoryOrderSelect|HistoryOrderGetDouble|HistoryOrderGetInteger|HistoryOrderGetString|HistoryOrderGetTicket|HistoryOrdersTotal|HistoryDealSelect|HistoryDealGetDouble|HistoryDealGetInteger|HistoryDealGetString|HistoryDealGetTicket|HistoryDealsTotal)\b</string>
					<key>name</key>
					<string>support.function.trade.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Symbol functions</string>
					<key>match</key>
					<string>\b(SymbolName|SymbolSelect|SymbolsTotal|SymbolIsSynchronized|SymbolInfoDouble|SymbolInfoInteger|SymbolInfoString|SymbolInfoTick|SymbolInfoMarginRate|SymbolInfoSessionQuote|SymbolInfoSessionTrade)\b</string>
					<key>name</key>
					<string>support.function.symbol.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Series/Timeseries functions</string>
					<key>match</key>
					<string>\b(CopyRates|CopyTime|CopyOpen|CopyHigh|CopyLow|CopyClose|CopyTickVolume|CopyRealVolume|CopySpread|CopyTicks|CopyTicksRange|SeriesInfoInteger|Bars|BarsCalculated|iBars|iBarShift|iClose|iHigh|iHighest|iLow|iLowest|iOpen|iTime|iVolume|iTickVolume|iSpread)\b</string>
					<key>name</key>
					<string>support.function.series.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Chart functions</string>
					<key>match</key>
					<string>\b(ChartApplyTemplate|ChartSaveTemplate|ChartWindowFind|ChartTimePriceToXY|ChartXYToTimePrice|ChartOpen|ChartFirst|ChartNext|ChartClose|ChartSymbol|ChartPeriod|ChartRedraw|ChartSetDouble|ChartSetInteger|ChartSetString|ChartGetDouble|ChartGetInteger|ChartGetString|ChartNavigate|ChartID|ChartIndicatorAdd|ChartIndicatorDelete|ChartIndicatorGet|ChartIndicatorName|ChartIndicatorsTotal|ChartScreenShot|ChartSetSymbolPeriod|ChartWindowOnDropped|ChartPriceOnDropped|ChartTimeOnDropped)\b</string>
					<key>name</key>
					<string>support.function.chart.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Object functions</string>
					<key>match</key>
					<string>\b(ObjectCreate|ObjectName|ObjectDelete|ObjectsDeleteAll|ObjectFind|ObjectGetDouble|ObjectGetInteger|ObjectGetString|ObjectSetDouble|ObjectSetInteger|ObjectSetString|ObjectMove|ObjectsTotal|ObjectGetTimeByValue|ObjectGetValueByTime)\b</string>
					<key>name</key>
					<string>support.function.object.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Indicator functions</string>
					<key>match</key>
					<string>\b(IndicatorCreate|IndicatorParameters|IndicatorRelease|CopyBuffer|SetIndexBuffer|PlotIndexSetDouble|PlotIndexSetInteger|PlotIndexSetString|PlotIndexGetInteger|IndicatorSetDouble|IndicatorSetInteger|IndicatorSetString)\b</string>
					<key>name</key>
					<string>support.function.indicator.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Array functions</string>
					<key>match</key>
					<string>\b(ArrayBsearch|ArrayCopy|ArrayCompare|ArrayFree|ArrayGetAsSeries|ArrayInitialize|ArrayFill|ArrayIsDynamic|ArrayIsSeries|ArrayMaximum|ArrayMinimum|ArrayPrint|ArrayRange|ArrayResize|ArraySetAsSeries|ArraySize|ArraySort|ArraySwap|ArrayReverse|ArrayInsert|ArrayRemove)\b</string>
					<key>name</key>
					<string>support.function.array.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Math functions</string>
					<key>match</key>
					<string>\b(MathAbs|MathArccos|MathArcsin|MathArctan|MathCeil|MathCos|MathExp|MathFloor|MathLog|MathLog10|MathMax|MathMin|MathMod|MathPow|MathRand|MathRound|MathSin|MathSqrt|MathSrand|MathTan|MathIsValidNumber|MathExpm1|MathLog1p|MathArccosh|MathArcsinh|MathArctanh|MathCosh|MathSinh|MathTanh|MathSwap|MathArctan2)\b</string>
					<key>name</key>
					<string>support.function.math.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 String functions</string>
					<key>match</key>
					<string>\b(StringAdd|StringBufferLen|StringCompare|StringConcatenate|StringFill|StringFind|StringFormat|StringGetCharacter|StringInit|StringLen|StringSetLength|StringReplace|StringReserve|StringSetCharacter|StringSplit|StringSubstr|StringToLower|StringToUpper|StringTrimLeft|StringTrimRight|StringToCharArray|StringToShortArray|CharArrayToString|ShortArrayToString|StringToColor|StringToDouble|StringToInteger|StringToTime|ColorToString|DoubleToString|IntegerToString|TimeToString|EnumToString)\b</string>
					<key>name</key>
					<string>support.function.string.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Date/Time functions</string>
					<key>match</key>
					<string>\b(TimeCurrent|TimeTradeServer|TimeLocal|TimeGMT|TimeGMTOffset|TimeDaylightSavings|TimeToStruct|StructToTime|PeriodSeconds)\b</string>
					<key>name</key>
					<string>support.function.datetime.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 File functions</string>
					<key>match</key>
					<string>\b(FileOpen|FileClose|FileDelete|FileMove|FileCopy|FileFlush|FileIsEnding|FileIsLineEnding|FileIsExist|FileSize|FileTell|FileSeek|FileGetInteger|FileReadArray|FileReadBool|FileReadDatetime|FileReadDouble|FileReadFloat|FileReadInteger|FileReadLong|FileReadNumber|FileReadString|FileReadStruct|FileWrite|FileWriteArray|FileWriteDouble|FileWriteFloat|FileWriteInteger|FileWriteLong|FileWriteString|FileWriteStruct|FileFindFirst|FileFindNext|FileFindClose|FolderCreate|FolderDelete|FolderClean)\b</string>
					<key>name</key>
					<string>support.function.file.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Conversion functions</string>
					<key>match</key>
					<string>\b(NormalizeDouble|CharToString|ShortToString|ColorToARGB|StringToCharArray|StringToShortArray|StringToColor|StringToDouble|StringToInteger|StringToTime)\b</string>
					<key>name</key>
					<string>support.function.conversion.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Common functions</string>
					<key>match</key>
					<string>\b(Alert|Comment|Print|PrintFormat|MessageBox|SendFTP|SendMail|SendNotification|Sleep|PlaySound|GetLastError|ResetLastError|SetUserError|GetTickCount|GetMicrosecondCount|DebugBreak|ExpertRemove|TerminalClose|CheckPointer|GetPointer|ZeroMemory)\b</string>
					<key>name</key>
					<string>support.function.common.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Terminal functions</string>
					<key>match</key>
					<string>\b(TerminalInfoDouble|TerminalInfoInteger|TerminalInfoString|MQLInfoInteger|MQLInfoString|Symbol|Period|Digits|Point)\b</string>
					<key>name</key>
					<string>support.function.terminal.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Global Variables functions</string>
					<key>match</key>
					<string>\b(GlobalVariableCheck|GlobalVariableTime|GlobalVariableDel|GlobalVariableGet|GlobalVariableName|GlobalVariableSet|GlobalVariableSetOnCondition|GlobalVariablesDeleteAll|GlobalVariablesFlush|GlobalVariablesTotal|GlobalVariableTemp)\b</string>
					<key>name</key>
					<string>support.function.globalvar.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Market functions</string>
					<key>match</key>
					<string>\b(MarketBookAdd|MarketBookRelease|MarketBookGet)\b</string>
					<key>name</key>
					<string>support.function.market.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Event functions</string>
					<key>match</key>
					<string>\b(EventSetTimer|EventSetMillisecondTimer|EventKillTimer|EventChartCustom)\b</string>
					<key>name</key>
					<string>support.function.event.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 OpenCL functions</string>
					<key>match</key>
					<string>\b(CLContextCreate|CLContextFree|CLGetInfoInteger|CLGetInfoString|CLGetDeviceInfo|CLProgramCreate|CLProgramFree|CLKernelCreate|CLKernelFree|CLSetKernelArg|CLSetKernelArgMem|CLSetKernelArgMemLocal|CLBufferCreate|CLBufferFree|CLBufferRead|CLBufferWrite|CLExecute|CLHandleType|CLExecutionStatus)\b</string>
					<key>name</key>
					<string>support.function.opencl.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Crypto functions</string>
					<key>match</key>
					<string>\b(CryptEncode|CryptDecode)\b</string>
					<key>name</key>
					<string>support.function.crypto.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Signal functions</string>
					<key>match</key>
					<string>\b(SignalBaseGetDouble|SignalBaseGetInteger|SignalBaseGetString|SignalBaseSelect|SignalBaseTotal|SignalInfoGetDouble|SignalInfoGetInteger|SignalInfoGetString|SignalInfoSetDouble|SignalInfoSetInteger|SignalSubscribe|SignalUnsubscribe)\b</string>
					<key>name</key>
					<string>support.function.signal.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Tester functions</string>
					<key>match</key>
					<string>\b(TesterStatistics|TesterWithdrawal|TesterStop|TesterDeposit|TesterHideIndicators|FrameAdd|FrameFilter|FrameFirst|FrameInputs|FrameNext|ParameterGetRange|ParameterSetRange)\b</string>
					<key>name</key>
					<string>support.function.tester.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Resource functions</string>
					<key>match</key>
					<string>\b(ResourceCreate|ResourceFree|ResourceReadImage|ResourceSave)\b</string>
					<key>name</key>
					<string>support.function.resource.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Text/Font functions</string>
					<key>match</key>
					<string>\b(TextSetFont|TextOut|TextGetSize)\b</string>
					<key>name</key>
					<string>support.function.text.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Custom Symbol functions</string>
					<key>match</key>
					<string>\b(CustomSymbolCreate|CustomSymbolDelete|CustomSymbolSetInteger|CustomSymbolSetDouble|CustomSymbolSetString|CustomSymbolSetMarginRate|CustomSymbolSetSessionQuote|CustomSymbolSetSessionTrade|CustomRatesDelete|CustomRatesReplace|CustomRatesUpdate|CustomTicksAdd|CustomTicksDelete|CustomTicksReplace)\b</string>
					<key>name</key>
					<string>support.function.customsymbol.mql5</string>
				</dict>
			</array>
		</dict>
		<key>functions_mql5_new</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>MQL5 Database/SQLite functions (Build 2265+)</string>
					<key>match</key>
					<string>\b(DatabaseOpen|DatabaseClose|DatabaseImport|DatabaseExport|DatabaseTableExists|DatabaseExecute|DatabasePrepare|DatabaseRead|DatabaseReadBind|DatabaseFinalize|DatabaseTransactionBegin|DatabaseTransactionCommit|DatabaseTransactionRollback|DatabaseColumnsCount|DatabaseColumnName|DatabaseColumnType|DatabaseColumnSize|DatabaseColumnText|DatabaseColumnInteger|DatabaseColumnLong|DatabaseColumnDouble|DatabaseColumnBlob|DatabaseReset|DatabaseBind|DatabaseBindArray|DatabasePrint)\b</string>
					<key>name</key>
					<string>support.function.database.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Calendar functions (Build 2190+)</string>
					<key>match</key>
					<string>\b(CalendarCountryById|CalendarEventById|CalendarValueById|CalendarEventByCountry|CalendarEventByCurrency|CalendarValueHistoryByEvent|CalendarValueHistory|CalendarValueLastByEvent|CalendarValueLast)\b</string>
					<key>name</key>
					<string>support.function.calendar.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 WebRequest</string>
					<key>match</key>
					<string>\b(WebRequest)\b</string>
					<key>name</key>
					<string>support.function.web.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Socket functions (Build 2390+)</string>
					<key>match</key>
					<string>\b(SocketCreate|SocketClose|SocketConnect|SocketIsConnected|SocketIsReadable|SocketIsWritable|SocketTimeouts|SocketRead|SocketSend|SocketTlsHandshake|SocketTlsCertificate|SocketTlsRead|SocketTlsReadAvailable|SocketTlsSend)\b</string>
					<key>name</key>
					<string>support.function.socket.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Matrix/Vector/AI functions (Build 3180+)</string>
					<key>match</key>
					<string>\b(MatrixAdd|MatrixSub|MatrixMul|MatrixDiv|MatrixTranspose|MatrixInverse|MatrixDet|MatrixNorm|MatrixEig|MatrixSVD|MatrixLU|MatrixQR|MatrixCholesky|VectorAdd|VectorSub|VectorMul|VectorDiv|VectorDot|VectorNorm|VectorSum|VectorMean|VectorStd|VectorVar|VectorMax|VectorMin|VectorArgmax|VectorArgmin|VectorSort|VectorResize|VectorFill|Activation|Loss|Derivative)\b</string>
					<key>name</key>
					<string>support.function.matrix.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 OpenBLAS Matrix functions (Build 3902+) - Advanced linear algebra</string>
					<key>match</key>
					<string>\b(MatrixBalance|MatrixGBalance|MatrixEigenVectors|MatrixEigenVectorsBackward|MatrixEigenVectorsQZ|MatrixEigenVectorsQZBackward|MatrixEigenValuesQZ|MatrixSchur|MatrixSchurReal|MatrixRSchur|MatrixHessenberg|ReduceToHessenbergForm|ReduceToHessenbergBalanced|MatrixTriangular|MatrixUpperTriangular|MatrixLowerTriangular|MatrixBand|MatrixUpperBand|MatrixLowerBand|MatrixTridiagonal|MatrixSymmetric|MatrixHermitian|MatrixPositiveDefinite|MatrixConditionNumber|MatrixRank|MatrixTrace|MatrixPinv|MatrixKronecker|MatrixOuter|MatrixHadamard|MatrixVectorize|MatrixReshape|MatrixFlatten|MatrixConcat|MatrixSplit|MatrixCopy|MatrixFill|MatrixZeros|MatrixOnes|MatrixEye|MatrixDiag|MatrixDiagonal|MatrixSubmatrix|MatrixSlice|MatrixSwapRows|MatrixSwapCols|MatrixPermuteRows|MatrixPermuteCols)\b</string>
					<key>name</key>
					<string>support.function.matrix-openblas.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Matrix Norm/Classification functions</string>
					<key>match</key>
					<string>\b(MatrixNorm1|MatrixNormInf|MatrixNormFro|MatrixNorm2|MatrixNormNuc|MatrixNormMax|MatrixIsSquare|MatrixIsSymmetric|MatrixIsHermitian|MatrixIsTriangular|MatrixIsDiagonal|MatrixIsBand|MatrixIsUpperTriangular|MatrixIsLowerTriangular|MatrixIsPositiveDefinite|MatrixIsPositiveSemiDefinite|MatrixIsNegativeDefinite|MatrixIsNegativeSemiDefinite|MatrixIsIndefinite|MatrixIsOrthogonal|MatrixIsUnitary|MatrixIsSingular|MatrixIsNormal|MatrixIsSkewSymmetric|MatrixIsSkewHermitian|MatrixIsPermutation|MatrixIsStochastic|MatrixIsDoublyStochastic|MatrixIsIdempotent|MatrixIsNilpotent|MatrixIsInvolutory)\b</string>
					<key>name</key>
					<string>support.function.matrix-classify.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Complex number functions</string>
					<key>match</key>
					<string>\b(ComplexReal|ComplexImag|ComplexAbs|ComplexArg|ComplexConj|ComplexNorm|ComplexPolar|ComplexExp|ComplexLog|ComplexSqrt|ComplexPow|ComplexSin|ComplexCos|ComplexTan|ComplexSinh|ComplexCosh|ComplexTanh)\b</string>
					<key>name</key>
					<string>support.function.complex.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 ONNX/ML functions (Build 3230+)</string>
					<key>match</key>
					<string>\b(OnnxCreate|OnnxCreateFromBuffer|OnnxRelease|OnnxRun|OnnxGetInputCount|OnnxGetOutputCount|OnnxGetInputName|OnnxGetOutputName|OnnxGetInputTypeInfo|OnnxGetOutputTypeInfo|OnnxSetInputShape|OnnxSetOutputShape)\b</string>
					<key>name</key>
					<string>support.function.onnx.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Python integration (Build 3650+)</string>
					<key>match</key>
					<string>\b(Python|PyCall|PyImport)\b</string>
					<key>name</key>
					<string>support.function.python.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>MQL5 Symbol position functions (recent)</string>
					<key>match</key>
					<string>\b(PositionClose|PositionCloseBy|PositionClosePartial|PositionModify|PositionOpen)\b</string>
					<key>name</key>
					<string>support.function.position.mql5</string>
				</dict>
			</array>
		</dict>
		<key>indicators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>MQL5 Technical Indicators</string>
					<key>match</key>
					<string>\b(iAC|iAD|iADX|iADXWilder|iAlligator|iAMA|iAO|iATR|iBands|iBearsPower|iBullsPower|iBWMFI|iCCI|iChaikin|iCustom|iDEMA|iDeMarker|iEnvelopes|iForce|iFractals|iFrAMA|iGator|iIchimoku|iMA|iMACD|iMFI|iMomentum|iOBV|iOsMA|iRSI|iRVI|iSAR|iStdDev|iStochastic|iTEMA|iTriX|iVIDyA|iVolumes|iWPR)\b</string>
					<key>name</key>
					<string>support.function.indicator.mql5</string>
				</dict>
			</array>
		</dict>
		<key>predefined_variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(_Symbol|_Period|_Point|_Digits|_LastError|_StopFlag|_UninitReason|_RandomSeed|_IsX64)\b</string>
					<key>name</key>
					<string>variable.language.predefined.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>DEPRECATED: MQL4-style predefined variables</string>
					<key>match</key>
					<string>\b(Ask|Bid|Bars|Close|High|Low|Open|Time|Volume|Point|Digits)\b(?!\s*\()</string>
					<key>name</key>
					<string>invalid.deprecated.mql4.predefined-variable.mql5</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|TRUE|FALSE|NULL|EMPTY|EMPTY_VALUE|WHOLE_ARRAY|WRONG_VALUE|INVALID_HANDLE|CLR_NONE|clrNONE)\b</string>
					<key>name</key>
					<string>constant.language.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ACCOUNT_\w+|CHART_\w+|CHARTEVENT_\w+|CL_\w+|COPY_TICKS_\w+|CRYPT_\w+|DEAL_\w+|DRAW_\w+|ERR_\w+|FILE_\w+|INDICATOR_\w+|INIT_\w+|MODE_\w+|OBJECT_\w+|OBJPROP_\w+|ORDER_\w+|PERIOD_\w+|PLOT_\w+|POSITION_\w+|PRICE_\w+|REASON_\w+|SERIES_\w+|SIGNAL_\w+|STAT_\w+|STYLE_\w+|SYMBOL_\w+|TERMINAL_\w+|TICK_FLAG_\w+|TRADE_\w+|TYPE_\w+)\b</string>
					<key>name</key>
					<string>support.constant.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(OBJ_\w+|CORNER_\w+|ANCHOR_\w+|ENUM_\w+|IND_\w+|MQL_\w+|MQL5_\w+)\b</string>
					<key>name</key>
					<string>support.constant.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(DATABASE_\w+|CALENDAR_\w+|SOCKET_\w+|ONNX_\w+)\b</string>
					<key>name</key>
					<string>support.constant.new.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Day of week constants</string>
					<key>match</key>
					<string>\b(SUNDAY|MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY)\b</string>
					<key>name</key>
					<string>support.constant.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Color constants</string>
					<key>match</key>
					<string>\b(clr[A-Z][a-zA-Z]+)\b</string>
					<key>name</key>
					<string>support.constant.color.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Numeric limits</string>
					<key>match</key>
					<string>\b(CHAR_MAX|CHAR_MIN|SHORT_MAX|SHORT_MIN|INT_MAX|INT_MIN|LONG_MAX|LONG_MIN|UCHAR_MAX|USHORT_MAX|UINT_MAX|ULONG_MAX|DBL_MAX|DBL_MIN|DBL_EPSILON|DBL_DIG|FLT_MAX|FLT_MIN|FLT_EPSILON|FLT_DIG)\b</string>
					<key>name</key>
					<string>support.constant.numeric-limits.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Math constants</string>
					<key>match</key>
					<string>\b(M_E|M_LOG2E|M_LOG10E|M_LN2|M_LN10|M_PI|M_PI_2|M_PI_4|M_1_PI|M_2_PI|M_2_SQRTPI|M_SQRT2|M_SQRT1_2)\b</string>
					<key>name</key>
					<string>support.constant.math.mql5</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\+\+|--|&amp;&amp;|\|\||==|!=|&lt;=|&gt;=|&lt;&lt;|&gt;&gt;|\+=|-=|\*=|/=|%=|&amp;=|\|=|\^=|&lt;&lt;=|&gt;&gt;=</string>
					<key>name</key>
					<string>keyword.operator.compound.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=|\+|-|&lt;|&gt;|!|\*|/|%|&amp;|\||\~|\^</string>
					<key>name</key>
					<string>keyword.operator.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?|:</string>
					<key>name</key>
					<string>keyword.operator.ternary.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,|;|\.</string>
					<key>name</key>
					<string>punctuation.separator.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>::</string>
					<key>name</key>
					<string>punctuation.accessor.scope.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>punctuation.accessor.pointer.mql5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(|\)|\[|\]</string>
					<key>name</key>
					<string>punctuation.bracket.mql5</string>
				</dict>
			</array>
		</dict>
		<key>numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Hexadecimal numbers</string>
					<key>match</key>
					<string>\b0[xX][0-9a-fA-F]+\b</string>
					<key>name</key>
					<string>constant.numeric.hex.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Binary numbers</string>
					<key>match</key>
					<string>\b0[bB][01]+\b</string>
					<key>name</key>
					<string>constant.numeric.binary.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Floating point with exponent</string>
					<key>match</key>
					<string>\b[0-9]+\.[0-9]*([eE][-+]?[0-9]+)?\b|\b[0-9]*\.[0-9]+([eE][-+]?[0-9]+)?\b|\b[0-9]+[eE][-+]?[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.float.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Decimal integers</string>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Color literals</string>
					<key>match</key>
					<string>C'[0-9a-fA-F,\s]+'</string>
					<key>name</key>
					<string>constant.numeric.color.mql5</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Datetime literals</string>
					<key>match</key>
					<string>D'[0-9\.\:\s]+'</string>
					<key>name</key>
					<string>constant.numeric.datetime.mql5</string>
				</dict>
			</array>
		</dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.block.mql5</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mql5</string>
	<key>uuid</key>
	<string>78b6f517-1ebb-4231-97dd-31e37c37f4fe</string>
</dict>
</plist>
